MVC/Models/ErrorViewModel.cs
using System;

namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Models/Livros.cs
namespace MVC
{
    public class Livros
    {
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
    }
}

MVC/Models/Modelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace MVC
{
    [DataContract]
    public class BaseModel
    {
        [DataMember]
        public int Id { get; protected set; }
    }

    public class Produto : BaseModel
    {
        public Produto()
        {

        }

        [Required]
        public string Codigo { get; private set; }
        [Required]
        public string Nome { get; private set; }
        [Required]
        public decimal Preco { get; private set; }

        public Produto(string codigo, string nome, decimal preco)
        {
            this.Codigo = codigo;
            this.Nome = nome;
            this.Preco = preco;
        }
    }

    public class Cadastro : BaseModel
    {
        public Cadastro()
        {
        }

        public virtual Pedido Pedido { get; set; }
        [Required]
        public string Nome { get; set; } = "";
        [Required]
        public string Email { get; set; } = "";
        [Required]
        public string Telefone { get; set; } = "";
        [Required]
        public string Endereco { get; set; } = "";
        [Required]
        public string Complemento { get; set; } = "";
        [Required]
        public string Bairro { get; set; } = "";
        [Required]
        public string Municipio { get; set; } = "";
        [Required]
        public string UF { get; set; } = "";
        [Required]
        public string CEP { get; set; } = "";
    }

    public class ItemPedido : BaseModel
    {
        [Required]
        public Pedido Pedido { get; private set; }
        [Required]
        public Produto Produto { get; private set; }
        [Required]
        public int Quantidade { get; private set; }
        [Required]
        public decimal PrecoUnitario { get; private set; }

        public ItemPedido()
        {

        }

        public ItemPedido(Pedido pedido, Produto produto, int quantidade, decimal precoUnitario)
        {
            Pedido = pedido;
            Produto = produto;
            Quantidade = quantidade;
            PrecoUnitario = precoUnitario;
        }
    }

    public class Pedido : BaseModel
    {
        public Pedido()
        {
            Cadastro = new Cadastro();
        }

        public Pedido(Cadastro cadastro)
        {
            Cadastro = cadastro;
        }
        public int CadastroFk { get; set; }
        public List<ItemPedido> Itens { get; private set; } = new List<ItemPedido>();
        [Required]
        public virtual Cadastro Cadastro { get; private set; }
    }
}

MVC/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Repositories;
using MVC.Repositories.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IProdutoRepository produtoRepository;
        private readonly IPedidoRepository pedidoRepository;
        public PedidoController(IProdutoRepository produtoRepository, IPedidoRepository pedidoRepository)
        {
            this.produtoRepository = produtoRepository;
            this.pedidoRepository = pedidoRepository;
        }

        public IActionResult Carrossel()
        {
            return View(produtoRepository.GetProduto());
        }

        public IActionResult Carrinho(string codigo)
        {
            if(!string.IsNullOrEmpty(codigo))
            {
                pedidoRepository.AddList(codigo);
            }

            Pedido pedido = pedidoRepository.GetPedido();
            return View(pedido.Itens);
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Resumo()
        {
            Pedido pedido = pedidoRepository.GetPedido();
            return View(pedido);
        }
    }
}

MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/Views/Pedido/Cadastro.cshtml
@{ 
    ViewData["title"] = "Cadastro";
}
<h3>Cadastro</h3>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label" for="nomeCliente">Nome do Cliente</label>
                <input type="text" class="form-control" id="nomeCliente" placeholder="Nome do Cliente">
            </div>
            <div class="form-group">
                <label class="control-label" for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label class="control-label" for="telefone">Telefone</label>
                <input type="text" class="form-control" id="telefone" placeholder="Telefone">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label" for="endereco">Endereço</label>
                <input type="text" class="form-control" id="endereco" placeholder="Endereço">
            </div>
            <div class="form-group">
                <label class="control-label" for="complemento">Complemento</label>
                <input type="text" class="form-control" id="complemento" placeholder="Complemento">
            </div>
            <div class="form-group">
                <label class="control-label" for="bairro">Bairro</label>
                <input type="text" class="form-control" id="bairro" placeholder="Bairro">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label" for="municipio">Município</label>
                <input type="text" class="form-control" id="municipio" placeholder="Município">
            </div>
            <div class="form-group">
                <label class="control-label" for="UF">UF</label>
                <select class="form-control single-select" name="UF">
                    <option selected value="">[Selecione o estado]</option>
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espírito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label" for="cep">CEP</label>
                <input type="text" class="form-control" id="cep" placeholder="CEP">
            </div>

            <div class="form-group">
                <a class="btn btn-success" asp-action="Carrossel">
                    Continuar Comprando
                </a>
            </div>
            <div class="form-group">
                <button type="submit"
                        class="btn btn-success">
                    Finalizar Pedido
                </button>
            </div>
        </div>
    </div>
</div>

MVC/Views/Pedido/Carrinho.cshtml
@{ 
    ViewData["title"] = "Carrinho";
}
@model  IList<ItemPedido>;

<h3>Meu Carrinho</h3>

<div class="panel panel-default">
    <div class="panel-heading">

        <div class="row">
            <div class="col-md-6">
                Item
            </div>
            <div class="col-md-2 text-center">
                Preço Unitário
            </div>
            <div class="col-md-2 text-center">
                Quantidade
            </div>
            <div class="col-md-2">
                <span class="pull-right">
                    Subtotal
                </span>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @foreach (var item in Model)
        {
        <div class="row row-center linha-produto">
            <div class="col-md-3">
                <img class="img-produto-carrinho" src="/images/produtos/large_@(item.Produto.Codigo).jpg" />
            </div>
            <div class="col-md-3">@(item.Produto.Nome)</div>
            <div class="col-md-2 text-center">R$ @(item.PrecoUnitario)</div>
            <div class="col-md-2 text-center">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-default">
                            <span class="glyphicon-minus"></span>
                        </button>
                    </span>
                    <input type="text" value="@(item.Quantidade)"
                           class="form-control text-center" />
                    <span class="input-group-btn">
                        <button class="btn btn-default">
                            <span class="glyphicon-plus"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                R$ <span class="pull-right" subtotal>
                    @(item.PrecoUnitario * item.Quantidade)
                </span>
            </div>
        </div>
        }
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-10">
                <span numero-itens>
                    Total: @(Model.Count())
                    itens
                </span>
            </div>
            <div class="col-md-2">
                Total: R$ <span class="pull-right" total>
                    @(Model.Sum(i => i.PrecoUnitario * i.Quantidade))
                </span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            <a class="btn btn-success" asp-action="Carrossel">
                Adicionar Produtos
            </a>
            <a class="btn btn-success" asp-action="Resumo">
                Resumo
            </a>
        </div>
    </div>
</div>

MVC/Views/Pedido/Carrossel.cshtml
@{ 
    ViewData["title"] = "Carrossel";
}

@model List<Produto>;

<h3>Catálogo</h3>


<div id="my-carousel" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @{ 
            const int NUMERO_PAGINA = 4;
            int paginas = (int)Math.Ceiling((double)Model.Count() / NUMERO_PAGINA);
        }

        @for(var pagina = 0; pagina < paginas; pagina ++)
        {
        <div class="item @(pagina == 0 ? "active" : "")">
            <div class="row">
                @{ 
                    var produtos = Model.Skip(pagina * NUMERO_PAGINA).Take(NUMERO_PAGINA);
                }

                @foreach(var produto in produtos)
                {
                <div class="col-md-3 col-sm-3 col-lg-3">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <img class="img-produto-carrossel" src="/images/produtos/large_@(produto.Codigo).jpg" />
                        </div>
                        <div class="panel-footer produto-footer">
                            <div class="produto-nome">@produto.Nome</div>
                            <div><h4><strong>R$ @produto.Preco</strong></h4></div>
                            <div class="text-center">
                                @Html.ActionLink("Adicionar", "Carrinho", "Pedido", new { codigo = produto.Codigo }, new {@class = "btn btn-success"})
                                <a asp-action="Carrinho"
                                   asp-route-codigo="@produto.Codigo"
                                   class="btn btn-success">Adicionar</a>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
        }
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

MVC/Views/Pedido/Resumo.cshtml
@{ 
    ViewData["title"] = "Resumo";
}

@model  Pedido;

<h3>Resumo do Pedido</h3>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <h3>Nº do Pedido: @(Model.Id)</h3>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h3>Seus Dados</h3>
                <div>Harry Porto</div>
                <div>(11) 1234-5678</div>
            </div>
            <div class="col-md-3">
                luara.da.silva@gmail.com
            </div>
            <div class="col-md-6">
                <h3>Endereço de Entrega</h3>
                <div>Rua dos Alfeneiros, no. 4 (embaixo da escada) - Little Whinging - Surrey - Reino Unido</div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-10">
                <h3>Item</h3>
            </div>
            <div class="col-md-2">
                <h3>Quantidade</h3>
            </div>
        </div>
        @foreach (var item in Model.Itens)
        {
            <div class="row">
                <div class="col-md-10">
                    <div>@(item.Produto.Nome)</div>
                </div>
                <div class="col-md-2">
                    <div class="pull-right">@(item.Quantidade)</div>
                </div>
            </div>
        }

    </div>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Casa do Código</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
   
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Casa do Código</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>